### PR TITLE
Modified from version 702. and work fine with less lag.

### PR DESCRIPTION
**Pull request by zerofo**

### CODE REVIEW

**Comment by zerofo** [comment]
no response

**Comment by zerofo** [comment]
No response

**Comment by sleirsgoevy** [comment]
AFAIK this loop never succeeds in more than 1 iteration.

**Comment by zerofo** [comment]
> AFAIK this loop never succeeds in more than 1 iteration.

Then it must be that I changed somewhere else, 
but I'm not sure those are correct. (Maybe it's just a rebuild of the last version of inline.asm.)

**Pull request closed without merging**
